version: "3.9"

services:
  db:
    image: postgres:16
    container_name: team_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: teamdb
    ports:
      - "5432:5432"